{% set name = "PyRSMQ" %}
{% set version = "0.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: b718f96a297bda003d31df978aa6c7467df331d2f881e2eab6307afea17993f8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - redis-py

test:
  requires:
    - python {{ python_min }}
  imports:
    - rsmq
    - rsmq.cmd
    - tests

about:
  home: https://mlasevich.github.io/PyRSMQ/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python Implementation of Redis SMQ
  dev_url: https://github.com/mlasevich/PyRSMQ

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
